events {}
http{
    include mime.types;
    server{
        listen 80;
        server_name 10.10.200.23;
        return 301 $scheme://www.google.com
        root /blog_project;
        if ( $arg_name = "ruhul" ){
            return 200 "Hello Ruhul";
        }
    }
    server{
        listen 9099;
        server_name 10.10.200.23;
        root /test_server/;
        location /about{ 
            return 200 "about-page";
        }
        location = /contact{
            return 200 "contact-page";
        }
    }
}
