worker_processes auto; # managing worker processes
user www-data;
# managing worker connections

events {
    worker_connections 1024;
}
http{
    include mime.types;
    # buffer size of POST submissions
    client_body_buffer_size 10k;
    client_max_body_size 8m;
    # Buffer size for headers
    client_header_buffer_size 1k;

    # Max time to receive client headers/body
    client_body_timeout 12s; # 12m, 12h, 12d, 10y
    client_header_timeout 12s;

    # Max time for the client accept/receive a response
    send_timeout 15;

    # Skip buffering for static files
    sendFile on;
    tcp_nopush on;

    location ~* \.(jpg|jpeg|png|gif|css|js)$ {
        expires 365d;
    }

    
    server{
        listen 80;
        server_name 10.10.200.23;
        return 301 $scheme://www.google.com
        root /blog_project;
        if ( $arg_name = "ruhul" ){
            return 200 "Hello Ruhul";
        }
    }
    server{
        listen 9099;
        server_name 10.10.200.23;
        root /test_server/;
        location /about{ 
            return 200 "about-page";
        }
        location = /contact{
            return 200 "contact-page";
        }
        location = /userData{
            access_log off;
            return 200 "success";
        }
        location = /myself{
            access_log /var/nginx/logs/userdatalogs/myself.logs;
            return 200;
        }
    }
}
