events {}
http{
    include       mime.types;
    # types{
    #     text/css css;
    #     text/html html;
    # }
    server{
        listen 80;
        server_name  10.10.200.23;

        root /blog_project;
    }

    server{
        listen 9099;
        server_name 10.10.200.23;
        root /test_project/; # inside index.html has to be diclared
    }
}